#!/bin/bash

source /usr/share/yunohost/helpers

ynh_script_progression "Installing Permit Alert binary..."
ynh_setup_source --dest_dir="$install_dir"

ynh_script_progression "Configuring web access and service..."
ynh_config_add_nginx
ynh_config_add_systemd
ynh_systemctl --action=restart
